import Head from 'next/head'
import { Poppins } from 'next/font/google';
import {
  About, Contact, Experience, Feedbacks,
  Hero, Navbar, Tech, Works, StarsCanvas
} from '../components';

const poppins = Poppins({
  weight: ['400', '600', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  });

export default function Home() {
  return (
    <>
      <Head>
        <title>3dportfilio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={poppins.className}>
        <About/>
      </main>
    </>
  )
}
